// @vitest-environment happy-dom
import { describe, expect, it, vi } from 'vitest'
import { createLaneCreation, reportSubCreateResult, reportSidebarError, sidebarError } from './feedback'

describe('lane creation feedback', () => {
  it('waits for the matching result and permits retry after failure', () => {
    const send = vi.fn(), close = vi.fn()
    const form = createLaneCreation('/repo', send, close)
    form.submit({ name: 'topic', branch: 'mako/topic' })
    form.submit({ name: 'topic' })
    expect(send).toHaveBeenCalledTimes(1)
    expect(form.pending()).toBe(true)
    expect(close).not.toHaveBeenCalled()
    reportSubCreateResult('/other', 'topic', null)
    reportSubCreateResult('/repo', 'different', null)
    expect(form.pending()).toBe(true)
    reportSubCreateResult('/repo', 'topic', 'branch already exists')
    expect(form.error()).toBe('branch already exists')
    expect(form.pending()).toBe(false)
    expect(close).not.toHaveBeenCalled()
    form.submit({ name: 'topic', branch: 'mako/new' })
    expect(form.error()).toBe(null)
    reportSubCreateResult('/repo', 'topic', null)
    expect(close).toHaveBeenCalledOnce()
    form.dispose()
  })
  it('routes concurrent forms without replacing global handlers', () => {
    const a = vi.fn(), b = vi.fn()
    const first = createLaneCreation('/a', vi.fn(), a)
    const second = createLaneCreation('/b', vi.fn(), b)
    first.submit({ name: 'same' }); second.submit({ name: 'same' })
    first.dispose()
    reportSubCreateResult('/b', 'same', null)
    reportSubCreateResult('/a', 'same', null)
    expect(a).not.toHaveBeenCalled()
    expect(b).toHaveBeenCalledOnce()
    second.dispose()
  })
  it('surfaces local send failures and general sidebar errors', () => {
    const form = createLaneCreation('/repo', () => { throw Error('offline') }, vi.fn())
    form.submit({ name: 'topic' })
    expect(form.pending()).toBe(false)
    expect(form.error()).toBe('offline')
    reportSidebarError('repo registration failed')
    expect(sidebarError()).toBe('repo registration failed')
    form.dispose()
  })
})

it('connects native sidebar dispatch to visible error and the matching form', async () => {
  const { openSidebarDispatch } = await import('./dispatch')
  const { installIpcBridge } = await import('./ipc')
  openSidebarDispatch()
  installIpcBridge()
  const close = vi.fn()
  const form = createLaneCreation('/repo', vi.fn(), close)
  form.submit({ name: 'topic' })
  ;(window as unknown as { vpSidebarDispatch: (m: unknown) => void }).vpSidebarDispatch({ t: 'sidebar:error', message: 'native failure' })
  expect(sidebarError()).toBe('native failure')
  ;(window as unknown as { vpSidebarDispatch: (m: unknown) => void }).vpSidebarDispatch({ t: 'sub:create_result', repo_path: '/repo', name: 'topic' })
  expect(close).toHaveBeenCalledOnce()
  form.dispose()
})
