//! server → webview push の codegen pipeline。
//!
//! `schema/vp-push.kdl` を SSOT に club-kdl-codegen で Rust enum + TS union を生成し、
//! committed location に書き出す:
//!
//!   - `src/generated/push.rs`                — Rust `PushEnvelope`
//!   - `webview/src/generated/Push.ts`        — TS discriminated union
//!
//! `tests/sidebar_ipc_codegen.rs`（JS → Rust の逆向き）と同じ慣習で、`cargo test -p vp-app` を
//! 回せば生成物は必ず最新化される。生成 Rust が壊れていれば vp-app lib の build が先に失敗する
//! ため、「生成物がコンパイル可能」はこの test crate がビルドされる時点で保証される。

use std::path::{Path, PathBuf};

use kdl_codegen::Emitter;
use kdl_codegen::emit::{RustEmitter, TypeScriptEmitter};
use kdl_codegen::parser::parse;

/// 生成 Rust ファイルの先頭ヘッダ。
///
/// codegen は `anyhow` / `chrono` / `uuid` / `HashMap` を無条件に import するが、push schema が
/// 使うのは `serde` だけ。未解決クレート参照を避けるため prelude をこのヘッダに差し替える。
const RUST_HEADER: &str = "// @generated by club-kdl-codegen — DO NOT EDIT.
// SSOT: crates/vp-app/schema/vp-push.kdl
// 再生成: cargo test -p vp-app --test push_codegen
#![allow(unused_imports, dead_code)]

use serde::{Deserialize, Serialize};
";

/// 生成 TS ファイルの先頭に足す VP 用ヘッダ (emitter 自身の banner の前に置く)。
const TS_HEADER: &str = "// SSOT: crates/vp-app/schema/vp-push.kdl
// 再生成: cargo test -p vp-app --test push_codegen
";

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// codegen の Rust 出力を VP 用に整える: 無条件 prelude を `RUST_HEADER` に差し替える。
fn render_rust(emitted: &str) -> String {
    let body_start = emitted
        .find("#[derive")
        .expect("生成 Rust に derive ブロックが無い");
    format!("{RUST_HEADER}\n{}", &emitted[body_start..])
}

#[test]
fn regenerates_push_bindings() {
    let root = manifest_dir();
    let schema_path = root.join("schema/vp-push.kdl");
    let schema_src = std::fs::read_to_string(&schema_path)
        .unwrap_or_else(|e| panic!("schema 読み込み失敗 {}: {e}", schema_path.display()));

    let schema = parse(&schema_src).expect("vp-push.kdl のパースに失敗");

    // --- Rust ---------------------------------------------------------------
    let rust_emitted = RustEmitter::new().emit(&schema);
    assert_eq!(
        rust_emitted,
        RustEmitter::new().emit(&schema),
        "Rust emitter の出力が非決定的"
    );
    let rust_file = render_rust(&rust_emitted);
    write_if_changed(&root.join("src/generated/push.rs"), &rust_file);

    // envelope enum が internally-tagged discriminated union として出ていること。
    // ここが崩れると Rust の serde 出力と TS の `switch (m.t)` が食い違い、**実行時に黙って
    // 何も起きない**（この境界に型が無かった時代の失敗そのもの）。
    assert!(rust_file.contains("#[serde(tag = \"t\")]"));
    // event 側の envelope は `{Channel}EventEnvelope`（request 側の `{Channel}Envelope` と
    // 別名）。channel は両方向を運べるので、生成側が 2 本に分けている
    // （club-kdl 0.12.0 / chronista-club/club-kdl#33）。
    assert!(rust_file.contains("pub enum PushEventEnvelope {"));
    assert!(
        !rust_file.contains("pub enum PushEnvelope {"),
        "request を持たない channel に request envelope が出ている"
    );
    // 識別子 sanitize: `:` 入り wire 名がそのまま型名に漏れていないこと。
    assert!(
        !rust_file.contains("struct term:"),
        "`:` 入りの raw 名が Rust 識別子に漏れている"
    );

    // --- TypeScript ---------------------------------------------------------
    let ts_emitted = TypeScriptEmitter::new().emit(&schema);
    assert_eq!(
        ts_emitted,
        TypeScriptEmitter::new().emit(&schema),
        "TypeScript emitter の出力が非決定的"
    );
    let ts_file = format!("{TS_HEADER}{ts_emitted}");
    write_if_changed(&root.join("webview/src/generated/Push.ts"), &ts_file);

    assert!(ts_file.contains("export type PushEventEnvelope ="));

    // schema の全 wire 名が Rust / TS 双方に出ていること。schema 編集で codegen から落ちると
    // Rust → JS の押し込みが silently 壊れるので regression net を張る。
    for wire in [
        "term:ensure_lane",
        "term:show_lane",
        "term:remove_lane",
        "term:remove_session",
        "term:paste",
    ] {
        assert!(rust_file.contains(wire), "Rust に wire 名 {wire} が無い");
        assert!(ts_file.contains(wire), "TS に wire 名 {wire} が無い");
    }
}

/// 内容が変わったときだけ書き込む (無変更なら git status / mtime を汚さない)。
fn write_if_changed(path: &Path, content: &str) {
    if std::fs::read_to_string(path).is_ok_and(|cur| cur == content) {
        return;
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("生成先ディレクトリの作成に失敗");
    }
    std::fs::write(path, content)
        .unwrap_or_else(|e| panic!("生成物の書き込み失敗 {}: {e}", path.display()));
}
