//! sidebar IPC の codegen pipeline (VP-208 Phase A)。
//!
//! `schema/vp-sidebar.kdl` を SSOT に club-kdl-codegen で Rust enum + TS union を
//! 生成し、 committed location に書き出す:
//!
//!   - `src/generated/sidebar_ipc.rs`            — Rust `IpcEnvelope`
//!   - `webview/src/generated/SidebarIpc.ts`  — TS discriminated union
//!
//! ts-rs の binding export と同じ慣習で、 `cargo test -p vp-app` を回せば生成物は
//! 必ず最新化される。 生成 Rust が壊れていれば vp-app lib の build が先に失敗するため、
//! 「生成物がコンパイル可能」 はこの test crate がビルドされる時点で保証される。
//!
//! PR-1 scope: 生成物を既存の手書き定義 (`webview/src/sidebar/ipc.ts` の
//! `SidebarIpcMsg` / `app.rs` の `handle_sidebar_ipc`) と並存させるのみ。
//! caller 移行は PR-2 (Rust) / PR-3 (TS)。

use std::path::{Path, PathBuf};

use kdl_codegen::Emitter;
use kdl_codegen::emit::{RustEmitter, TypeScriptEmitter};
use kdl_codegen::parser::parse;

/// 生成 Rust ファイルの先頭ヘッダ。
///
/// codegen は `anyhow` / `chrono` / `uuid` / `HashMap` を無条件に import するが、
/// sidebar schema が使うのは `serde` だけ。 未解決クレート参照を避けるため
/// prelude をこのヘッダに差し替える。 生成物は手書きでない & 未使用要素を含むので
/// `#![allow(unused_imports, dead_code)]` を付ける。
const RUST_HEADER: &str = "// @generated by club-kdl-codegen — DO NOT EDIT.
// SSOT: crates/vp-app/schema/vp-sidebar.kdl
// 再生成: cargo test -p vp-app --test sidebar_ipc_codegen
#![allow(unused_imports, dead_code)]

use serde::{Deserialize, Serialize};
";

/// 生成 TS ファイルの先頭に足す VP 用ヘッダ (emitter 自身の banner の前に置く)。
const TS_HEADER: &str = "// SSOT: crates/vp-app/schema/vp-sidebar.kdl
// 再生成: cargo test -p vp-app --test sidebar_ipc_codegen
";

/// crate root (`crates/vp-app`) の絶対パス。
fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// codegen の Rust 出力を VP 用に整える: 無条件 prelude を `RUST_HEADER` に差し替える。
fn render_rust(emitted: &str) -> String {
    let body_start = emitted
        .find("#[derive")
        .expect("生成 Rust に derive ブロックが無い");
    format!("{RUST_HEADER}\n{}", &emitted[body_start..])
}

#[test]
fn regenerates_sidebar_ipc_bindings() {
    let root = manifest_dir();
    let schema_path = root.join("schema/vp-sidebar.kdl");
    let schema_src = std::fs::read_to_string(&schema_path)
        .unwrap_or_else(|e| panic!("schema 読み込み失敗 {}: {e}", schema_path.display()));

    let schema = parse(&schema_src).expect("vp-sidebar.kdl のパースに失敗");

    // --- Rust ---------------------------------------------------------------
    let rust_emitted = RustEmitter::new().emit(&schema);
    // codegen の出力は決定的 (= 2 回 emit してバイト一致) であることを確認。
    assert_eq!(
        rust_emitted,
        RustEmitter::new().emit(&schema),
        "Rust emitter の出力が非決定的"
    );
    let rust_file = render_rust(&rust_emitted);
    write_if_changed(&root.join("src/generated/sidebar_ipc.rs"), &rust_file);

    // 識別子 sanitize: `:` 入り wire 名がそのまま型名に漏れていないこと。
    assert!(
        !rust_file.contains("struct process:"),
        "`:` 入りの raw 名が Rust 識別子に漏れている"
    );
    // envelope enum が internally-tagged discriminated union として出ていること。
    assert!(rust_file.contains("#[serde(tag = \"t\")]"));
    assert!(rust_file.contains("pub enum IpcEnvelope {"));
    // fieldless request → unit variant。
    assert!(rust_file.contains("    RepoAdd,\n"));
    assert!(rust_file.contains("    RepoClonePickFolder,\n"));
    // wire 名は serde rename で保持 (`:` 2 個の最難ケース含む)。
    assert!(rust_file.contains("#[serde(rename = \"repo:clone:pickFolder\")]"));

    // --- TypeScript ---------------------------------------------------------
    let ts_emitted = TypeScriptEmitter::new().emit(&schema);
    assert_eq!(
        ts_emitted,
        TypeScriptEmitter::new().emit(&schema),
        "TypeScript emitter の出力が非決定的"
    );
    let ts_file = format!("{TS_HEADER}{ts_emitted}");
    write_if_changed(&root.join("webview/src/generated/SidebarIpc.ts"), &ts_file);

    assert!(ts_file.contains("export type IpcEnvelope ="));
    assert!(ts_file.contains("({ t: \"repo:clone:pickFolder\" } & RepoClonePickFolder)"));

    // schema の全 13 request の wire 名が Rust / TS 双方に出ていること。
    for wire in [
        "process:toggle",
        "process:reorder",
        "process:restart",
        "process:stop",
        "repo:delete",
        "repo:add",
        "lane:select",
        "lane:delete",
        "lane:restart",
        "lane:add_sub",
        "agents:fetch",
        "stand:select",
        "repo:clone:pickFolder",
        // in-app update: sidebar footer の「更新する」ボタン。schema 編集で codegen から
        // 落ちると button → Rust dispatch が silently 壊れるので regression net を張る。
        "update:apply",
        // server → client（doc 53 §6.5.1.3）。同じ channel が両方向を運ぶ。
        "sidebar:state",
        "sidebar:error",
        "sub:create_result",
        "agents:result",
        "wire:result",
        "clone:path_picked",
        // （旧 `files:list_result` / `file_picker:open` は code pane 化で退役 —
        //   File Explorer overlay picker の sidebar channel ごと撤去。後継は
        //   main webview 側の `code:entries` / `code:toggle`、vp-push.kdl の網羅）
    ] {
        assert!(rust_file.contains(wire), "Rust に wire 名 {wire} が無い");
        assert!(ts_file.contains(wire), "TS に wire 名 {wire} が無い");
    }

    // request / event で **別名の envelope** が出ること（club-kdl 0.12.0 / club-kdl#33）。
    // 1 本に混ざると、client が送れないはずの event を送れてしまい型が意味を失う。
    assert!(rust_file.contains("pub enum IpcEventEnvelope {"));
    assert!(ts_file.contains("export type IpcEventEnvelope ="));
}

/// 内容が変わったときだけ書き込む (無変更なら git status / mtime を汚さない)。
fn write_if_changed(path: &Path, content: &str) {
    if std::fs::read_to_string(path).is_ok_and(|cur| cur == content) {
        return;
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("生成先ディレクトリ作成失敗");
    }
    std::fs::write(path, content)
        .unwrap_or_else(|e| panic!("生成物の書き込み失敗 {}: {e}", path.display()));
}
